name: Certificate Scraper Automation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch: # Allows manual execution

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas selenium

      - name: Set up Chrome WebDriver (for Selenium)
        run: |
          sudo apt update
          sudo apt install -y unzip
          wget -q https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Run Coursera Scraper
        run: python coursera_scraper.py

      - name: Run Credly Scraper
        run: python credly_scraper.py

      - name: Check if CSVs Changed
        run: |
          git diff --quiet Coursera_Certificates.csv Credly_Certificates.csv || echo "Changes detected"

      - name: Commit and Push Updated CSVs (If Changed)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Coursera_Certificates.csv Credly_Certificates.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated Certificates"
          git push
